version: '3'

services:
  booklibrary.aspnetcore.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  booklibrary.aspnetcore.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

